### PR TITLE
Improved Offender Searching

### PR DESCRIPTION
**Pull request by trainordevs**
This PR will improve the way an offender is searched through the database. Sometimes upon save, the order of firstname and lastname are reversed, causing the query to return empty when searching a full name.

New lines and functions are commented with their purpose. If you have any questions, feel free to reach out to me.

THERE ARE NOT THAT MANY ADDITIONS AND DELETIONS. VSCODE DECIDED TO FORMAT THE FILE AND GITHUB THINKS I MADE MAJOR CHANGES.

MY CHANGES ARE ON THESE LINES:
46 - 87, 656 - 672

### CODE REVIEW

**Comment by ItsVinnyX** [comment]
@trainordevs Hey man! Nice commit, was definitely needed. Hopefully, it gets pushed. So I have implemented some changes with the current MDT with functionality to search for fingerprints.

This was the code to do so. However, I implemented your branch and cannot seem to figure out how to exactly get the fingerprint searching mechanic back. Any thoughts?
```lua
RegisterServerEvent("mdt:performOffenderSearch")
AddEventHandler("mdt:performOffenderSearch", function(query)
	local usource = source
	local matches = {}
	exports.oxmysql:fetch("SELECT * FROM `players` WHERE `charinfo` LIKE ? OR `metadata` LIKE ?", {string.lower('%'..query..'%'),string.lower('%'..query..'%')}, function(result)
		for index, data in ipairs(result) do
			if data.charinfo then
				local player = json.decode(data.charinfo)
				local metadata = json.decode(data.metadata)
				local core = QBCore.Functions.GetPlayerByCitizenId(data.citizenid)

				if core then
					player = core['PlayerData']['charinfo']
					metadata = core['PlayerData']['metadata']
				end

				player.id = data.id
				player.metadata = metadata
				player.bloodtype = metadata.bloodtype
				player.fingerprint = metadata.fingerprint
				player.citizenid = data.citizenid
				table.insert(matches, player)
			end
		end

		TriggerClientEvent("mdt:returnOffenderSearchResults", usource, matches)
	end)
end)```

**Comment by trainordevs** [comment]
From the looks of it, you only need to add 2 more lines to the push...
```
player.bloodtype = metadata.bloodtype
player.fingerprint = metadata.fingerprint
```

If you add these before the table.insert(matches, player), it will push their blood type and fingerprint.`

It should look like this:
```
local player = json.decode(data.charinfo)
local metadata = json.decode(data.metadata)
local core = QBCore.Functions.GetPlayerByCitizenId(data.citizenid)
if core then
    player = core['PlayerData']['charinfo']
    metadata = core['PlayerData']['metadata']
end
player.id = data.id
player.metadata = metadata
player.citizenid = data.citizenid
player.bloodtype = metadata.bloodtype
player.fingerprint = metadata.fingerprint

table.insert(matches, player)
```

**Comment by ItsVinnyX** [comment]
> From the looks of it, you only need to add 2 more lines to the push...
> 
> ```
> player.bloodtype = metadata.bloodtype
> player.fingerprint = metadata.fingerprint
> ```
> 
> If you add these before the table.insert(matches, player), it will push their blood type and fingerprint.`
> 
> It should look like this:
> 
> ```
> local player = json.decode(data.charinfo)
> local metadata = json.decode(data.metadata)
> local core = QBCore.Functions.GetPlayerByCitizenId(data.citizenid)
> if core then
>     player = core['PlayerData']['charinfo']
>     metadata = core['PlayerData']['metadata']
> end
> player.id = data.id
> player.metadata = metadata
> player.citizenid = data.citizenid
> player.bloodtype = metadata.bloodtype
> player.fingerprint = metadata.fingerprint
> 
> table.insert(matches, player)
> ```

Oh thanks, I appreciate that. I will probably most likely push it to the git later today!

**Comment by ItsVinnyX** [comment]
Full name searches work fine, however, fingerprint search just does the loading search result like full names do prior to this push,

**Comment by trainordevs** [comment]
In all honesty, fingerprint searching has never been a thing for me. The offender search should've never been returning results based off a fingerprint because that is in a completely and utterly different database column than charinfo.

If you wanted to make fingerprint searching work, you'd need to add an additional query to check the `metadata` column for a match with wildcards ("%?%") where '?' is your query. Then, you have to grab the row number from that query and run another query against the table to grab the row with the previously pulled id so that you could get the character information. Then you'd have to add that player to the matches table before it sends the information to the NUI.

**Comment by ItsVinnyX** [comment]
Actually not sure if there's a better way or simplistic, I managed to do it.
```lua
    exports.oxmysql:fetch("SELECT * FROM `players` WHERE `charinfo` LIKE ? OR `charinfo` LIKE ?", {queryReplacement, queryReplacement1}, function(result)
		for index, data in ipairs(result) do
			if data.charinfo then
                local player = json.decode(data.charinfo)
                local metadata = json.decode(data.metadata)
                local core = QBCore.Functions.GetPlayerByCitizenId(data.citizenid)
                if core then
                    player = core['PlayerData']['charinfo']
                    metadata = core['PlayerData']['metadata']
                end
                player.id = data.id
                player.metadata = metadata
                player.citizenid = data.citizenid
                player.bloodtype = metadata.bloodtype
                player.fingerprint = metadata.fingerprint

                table.insert(matches, player)
			end
		end

		TriggerClientEvent("mdt:returnOffenderSearchResults", usource, matches)
	end)
    
	exports.oxmysql:fetch("SELECT * FROM `players` WHERE `charinfo` LIKE ? OR `metadata` LIKE ?", {string.lower('%'..query..'%'),string.lower('%'..query..'%')}, function(result) -- % wildcard, needed to search for all alike results
		for index, data in ipairs(result) do
			if data.charinfo then
				local player = json.decode(data.charinfo)
				local metadata = json.decode(data.metadata)
				local core = QBCore.Functions.GetPlayerByCitizenId(data.citizenid)

				if core then
					player = core['PlayerData']['charinfo']
					metadata = core['PlayerData']['metadata']
				end

				player.id = data.id
				player.metadata = metadata
				player.bloodtype = metadata.bloodtype
				player.fingerprint = metadata.fingerprint
				player.citizenid = data.citizenid
				table.insert(matches, player)
			end
		end

		TriggerClientEvent("mdt:returnOffenderSearchResults", usource, matches)
	end)
	```

**Pull request closed without merging**
